name: 🐛 Bug Report
description: 버그 또는 오류를 신고합니다
title: "[BUG] "
labels: ["BUG"]
assignees:
  - zzzz955

body:
  - type: markdown
    attributes:
      value: |
        버그를 발견하셨나요? 아래 정보를 간단히 작성해주세요.

  - type: textarea
    id: description
    attributes:
      label: 버그 설명
      description: 어떤 문제가 발생했나요?
      placeholder: 간단히 설명해주세요
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 재현 방법
      description: 어떻게 이 버그를 다시 발생시킬 수 있나요?
      placeholder: |
        1. 어디로 가서
        2. 무엇을 클릭하고
        3. 어떤 결과가 나타났나요
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: 기대 동작
      description: 원래 어떻게 동작해야 하나요?
      placeholder: 예상했던 동작을 설명해주세요
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 스크린샷, 에러 로그 등 추가 정보가 있다면 첨부해주세요
      placeholder: 선택사항
    validations:
      required: false